"""Plugin to register 'TestBot1' robot environment.

This module is auto-generated by the GUI. It registers a factory that builds
a VecEnv for the robot using the manager's parameters.
"""

from common.rl_coppelia_manager import RLCoppeliaManager
from stable_baselines3.common.env_util import make_vec_env
from robots.TestBot1.envs import Testbot1Env

def _factory(manager: RLCoppeliaManager):
    """Create a VecEnv instance for 'TestBot1'.

    Args:
        manager: The current RLCoppeliaManager instance.

    Returns:
        A vectorized environment (VecEnv) suitable for training/testing.
    """
    return make_vec_env(
        Testbot1Env,
        n_envs=1,
        monitor_dir=manager.log_monitor,
        env_kwargs={
            "params_env": manager.params_env,
            "comms_port": manager.free_comms_port,
        },
    )

# Register on module import
RLCoppeliaManager.register_robot("TestBot1", _factory)
